---
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Linter
        language: system
        types: [python]
        entry: poetry run ruff check --fix
        require_serial: true
        stages: [pre-commit, pre-push, manual]
      - id: ruff-format
        name: Ruff Formatter
        language: system
        types: [python]
        entry: poetry run ruff format
        require_serial: true
        stages: [pre-commit, pre-push, manual]
      - id: codespell
        name: Check code for common misspellings
        language: system
        types: [text]
        exclude: ^(poetry\.lock$|custom_components/omnik_inverter/translations/)
        args: [--ignore-words=.codespell-ignore, --skip=./custom_components/omnik_inverter/translations]
        entry: poetry run codespell
      - id: mypy
        name: Static type checking using mypy
        language: system
        types: [python]
        entry: poetry run mypy
        require_serial: true
      - id: poetry
        name: Check pyproject with Poetry
        language: system
        entry: poetry check
        pass_filenames: false
        always_run: true
      - id: pylint
        name: Starring code with pylint
        language: system
        types: [python]
        entry: poetry run pylint
      - id: yamllint
        name: Check YAML files with yamllint
        language: system
        types: [yaml]
        entry: poetry run yamllint
  - repo: builtin
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        stages: [pre-commit, pre-push, manual]
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        stages: [pre-commit, pre-push, manual]
      - id: no-commit-to-branch
        args:
          - --branch=main
      - id: trailing-whitespace
        stages: [pre-commit, pre-push, manual]
